require 'spec_helper'
require 'tmpdir'

# Unit specs for the pure decision logic in hyperstack:install.
#
# These exist because two bugs in exactly this logic reached CI and cost a
# full pipeline each to diagnose, even though both are decidable from a string
# in a temp directory (#51):
#
#   * new_rails_app? counted Rails 7's built-in routes as user routes, so a
#     freshly generated app looked like an existing project and the top-level
#     App component was silently skipped.
#   * the generated layout never got a javascript_include_tag, so the sprockets
#     bundle -- and with it Opal and the whole client -- never loaded.
#
# Nothing here boots an app or a browser: each example writes a fixture file,
# runs one generator method against it, and asserts on the result.
describe 'hyperstack:install generator logic' do
  let(:app_dir) { Dir.mktmpdir('hyperstack-install-spec') }

  # A generator instance rooted at the temp dir. Thor only runs commands on
  # .start, so .new is inert and individual methods can be called directly.
  let(:generator) do
    Hyperstack::InstallGenerator.new([], {}, destination_root: app_dir, verbose: false)
  end

  before do
    allow(::Rails).to receive(:root).and_return(Pathname.new(app_dir))
  end

  # new_rails_app? is private and js_pipeline_name protected -- deliberately, they
  # are internal decisions, not part of the generator's command surface (Thor turns
  # public methods into install steps). They are still worth pinning directly, so
  # these call through send rather than widening the real API for the tests.

  after { FileUtils.remove_entry(app_dir) if File.exist?(app_dir) }

  def write(relative, contents)
    path = File.join(app_dir, relative)
    FileUtils.mkdir_p(File.dirname(path))
    File.write(path, contents)
    path
  end

  describe '#new_rails_app?' do
    # As generated by `rails _6.1_ new`.
    let(:rails61_routes) { <<~RUBY }
      Rails.application.routes.draw do
        # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
      end
    RUBY

    # As generated by `rails _7.2_ new` -- ships three built-in routes.
    let(:rails72_routes) { <<~RUBY }
      Rails.application.routes.draw do
        # Reveal health status on /up that returns 200 if the app boots with no exceptions.
        get "up" => "rails/health#show", as: :rails_health_check

        # Render dynamic PWA files from app/views/pwa/*
        get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
        get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

        # Defines the root path route ("/")
        # root "posts#index"
      end
    RUBY

    it 'treats a freshly generated Rails 6.1 app as new' do
      write('config/routes.rb', rails61_routes)
      expect(generator.send(:new_rails_app?)).to be true
    end

    # The #10 regression: without the rails/* filter this counts 5 and the
    # installer skips generating the App component entirely.
    it 'treats a freshly generated Rails 7.2 app as new, ignoring its built-in routes' do
      write('config/routes.rb', rails72_routes)
      expect(generator.send(:new_rails_app?)).to be true
    end

    it 'does not treat an app with real user routes as new' do
      write('config/routes.rb', <<~RUBY)
        Rails.application.routes.draw do
          resources :posts
          resources :comments
          root "posts#index"
        end
      RUBY
      expect(generator.send(:new_rails_app?)).to be false
    end

    it 'ignores mounted engines, so installing twice still sees a new app' do
      write('config/routes.rb', <<~RUBY)
        Rails.application.routes.draw do
          mount Hyperstack::Engine => '/hyperstack'
        end
      RUBY
      expect(generator.send(:new_rails_app?)).to be true
    end

    it 'ignores comments and blank lines' do
      write('config/routes.rb', <<~RUBY)
        Rails.application.routes.draw do

          # resources :posts
          # resources :comments

        end
      RUBY
      expect(generator.send(:new_rails_app?)).to be true
    end
  end

  describe '#insure_layout_loads_javascript' do
    let(:layout) { 'app/views/layouts/application.html.erb' }

    # As generated by `rails _7.2_ new --skip-javascript`: no javascript tag at all.
    let(:layout_without_js) { <<~ERB }
      <!DOCTYPE html>
      <html>
        <head>
          <title>Test App</title>
          <%= csrf_meta_tags %>
          <%= stylesheet_link_tag "application" %>
        </head>
        <body>
          <%= yield %>
        </body>
      </html>
    ERB

    # The #9 regression: without this the client never loads and / renders blank.
    it 'adds the include tag when the layout has no javascript tag' do
      write(layout, layout_without_js)
      generator.insure_layout_loads_javascript
      contents = File.read(File.join(app_dir, layout))
      expect(contents).to include("<%= javascript_include_tag 'application' %>")
      expect(contents.index('javascript_include_tag')).to be < contents.index('</head>')
    end

    it 'leaves a layout that already loads the bundle alone' do
      write(layout, layout_without_js.sub(
        '</head>', "  <%= javascript_include_tag \"application\" %>\n  </head>"
      ))
      before_contents = File.read(File.join(app_dir, layout))
      generator.insure_layout_loads_javascript
      expect(File.read(File.join(app_dir, layout))).to eq(before_contents)
    end

    it 'is idempotent, so re-running the installer does not stack tags' do
      write(layout, layout_without_js)
      generator.insure_layout_loads_javascript
      generator.insure_layout_loads_javascript
      expect(File.read(File.join(app_dir, layout)).scan('javascript_include_tag').size).to eq(1)
    end

    it 'does nothing when there is no layout to patch' do
      expect { generator.insure_layout_loads_javascript }.not_to raise_error
    end
  end

  # The pipeline strategies are the one place the codebase legitimately forks on
  # version (Webpacker and esbuild scaffold different applications). The fork is
  # dispatched by extending a module at run time, so a rename or a mis-nested
  # module is invisible until an install actually runs -- which is how three
  # bugs got into CI during the strategy refactor. Pin the wiring instead.
  describe '#js_pipeline_strategy' do
    around do |example|
      saved = ENV['HYPERSTACK_JS_PIPELINE']
      example.run
      ENV['HYPERSTACK_JS_PIPELINE'] = saved
    end

    it 'selects the Webpacker strategy' do
      ENV['HYPERSTACK_JS_PIPELINE'] = 'webpacker'
      expect(generator.send(:js_pipeline_strategy))
        .to eq(::Rails::Generators::JsPipeline::Webpacker)
    end

    it 'selects the esbuild strategy' do
      ENV['HYPERSTACK_JS_PIPELINE'] = 'esbuild'
      expect(generator.send(:js_pipeline_strategy))
        .to eq(::Rails::Generators::JsPipeline::Esbuild)
    end

    it 'refuses an unknown pipeline rather than silently picking one' do
      ENV['HYPERSTACK_JS_PIPELINE'] = 'parcel'
      expect { generator.send(:js_pipeline_strategy) }
        .to raise_error(Thor::Error, /parcel/)
    end

    # Both strategies must answer the whole dispatch surface: install_webpack and
    # webpack_check extend the module and immediately call these.
    [::Rails::Generators::JsPipeline::Webpacker,
     ::Rails::Generators::JsPipeline::Esbuild].each do |strategy|
      it "#{strategy.name.split('::').last} implements the full strategy interface" do
        expect(strategy.instance_methods).to include(:install_js_pipeline, :pipeline_webpack_check)
      end

      # The add-on framework generators (install_mui, install_bootstrap) extend a
      # strategy and call these three. They used to hardcode the Webpacker answer,
      # which silently did nothing on an esbuild app -- the pack manifest they
      # appended to is not read by esbuild, so the global was simply never defined.
      # Both strategies must answer, or the add-on generator NoMethodErrors on one
      # pipeline and no spec would say which. (#98)
      it "#{strategy.name.split('::').last} implements the add-on generator surface" do
        expect(strategy.instance_methods)
          .to include(:expose_npm_global, :add_npm_stylesheet, :build_js_bundle, :insure_yarn_loaded)
      end

      # Signatures too, not just presence: the generators call
      # expose_npm_global(global, package) and add_npm_stylesheet(scss_path:, cdn_url:),
      # so a strategy that defines the names with different arity still breaks at the
      # call site, on one pipeline only.
      it "#{strategy.name.split('::').last} matches the add-on generator signatures" do
        expect(strategy.instance_method(:expose_npm_global).arity).to eq(2)
        required_keywords = strategy.instance_method(:add_npm_stylesheet)
                                    .parameters.select { |type, _| type == :keyreq }
                                    .map(&:last).sort
        expect(required_keywords).to eq(%i[cdn_url scss_path])
      end
    end

    # The strategies are nested under Rails::Generators::JsPipeline, NOT under
    # Hyperstack: defining a partial Hyperstack constant at generator-load time
    # broke the app boot with an unrelated Logger NameError. (#51)
    it 'namespaces the strategies outside the Hyperstack module' do
      expect(defined?(::Hyperstack::JsPipeline)).to be_nil
    end
  end

  describe '#js_pipeline_name' do
    around do |example|
      saved = ENV['HYPERSTACK_JS_PIPELINE']
      example.run
      ENV['HYPERSTACK_JS_PIPELINE'] = saved
    end

    it 'honours an explicit HYPERSTACK_JS_PIPELINE, whatever Rails is running' do
      ENV['HYPERSTACK_JS_PIPELINE'] = 'webpacker'
      expect(generator.send(:js_pipeline_name)).to eq('webpacker')
      ENV['HYPERSTACK_JS_PIPELINE'] = 'esbuild'
      expect(generator.send(:js_pipeline_name)).to eq('esbuild')
    end

    # Pins the mapping so it cannot silently invert: Rails 7 has no
    # webpacker:install, Rails < 7 predates the esbuild scaffolding.
    it 'defaults on the Rails major version' do
      ENV.delete('HYPERSTACK_JS_PIPELINE')
      expected = ::Rails::VERSION::MAJOR >= 7 ? 'esbuild' : 'webpacker'
      expect(generator.send(:js_pipeline_name)).to eq(expected)
    end
  end
end
