source 'https://rubygems.org'
#gem "opal-jquery", git: "https://github.com/opal/opal-jquery.git", branch: "master"
gem 'hyper-spec',        path: '../hyper-spec'
gem 'hyperstack-config', path: '../hyperstack-config'
gem 'hyper-store',       path: '../hyper-store'
gem 'hyper-state',       path: '../hyper-state'
# unless ENV['OPAL_VERSION']&.match("0.11")
#   gem 'opal-browser', git: 'https://github.com/opal/opal-browser'
# end
gem 'hyper-trace',       path: '../hyper-trace'

#gem 'puma', '~> 3.11.0' # As of adding, version 3.12.0 isn't working so we are locking

# CI/test harness: pin transitive deps to versions compatible with react-rails
# (< 2.7.0). sprockets >= 4.2 raises "can't modify immutable cached environment";
# connection_pool >= 3.0 breaks react-rails' server-renderer pool.
gem 'sprockets', '~> 4.0', '< 4.2'
gem 'connection_pool', '< 3.0'
gemspec

# Ruby 3.4 dropped several gems from the default set (now "bundled gems"), but
# Rails 6.1.7.x (activesupport) still requires them. Declare them explicitly so
# the bundle resolves on Ruby >= 3.4. See #11 (3.3 -> 3.4 bump).
gem 'bigdecimal'
gem 'mutex_m'
gem 'drb'
gem 'base64'
gem 'logger'
