source 'https://rubygems.org'
gem 'hyperstack-config', path: '../hyperstack-config'
gem 'hyper-state',       path: '../hyper-state'
gem 'hyper-component',   path: '../hyper-component'
gem 'hyper-operation',   path: '../hyper-operation'
gem 'hyper-model',       path: '../hyper-model'
gem 'hyper-router',      path: '../hyper-router'
gem 'hyper-spec',        path: '../hyper-spec'
gem 'webpacker'  # TODO: figure out why these two are necessary!
gem 'turbolinks'
gem "selenium-webdriver" #, '3.142.7'

# CI/test harness: pin transitive deps to versions compatible with react-rails
# (< 2.7.0). sprockets >= 4.2 raises "can't modify immutable cached environment";
# connection_pool >= 3.0 breaks react-rails' server-renderer pool.
gem 'sprockets', '~> 4.0', '< 4.2'
gem 'connection_pool', '< 3.0'
gemspec
