require "bundler/gem_tasks"
require "rspec/core/rake_task"
require 'pry'

RSpec::Core::RakeTask.new(:spec) do |t|
  t.rspec_opts = ENV['SPEC_OPTS'] if ENV['SPEC_OPTS']
end

namespace :spec do
  task :prepare do
    rails_version = `bundle info rails`.match(/\* rails \((.+)\)/)[1]
    opal_version = `bundle info opal`.match(/\* opal \((.+)\)/)[1]
    Dir.chdir('spec') do
      sh('rm -rf test_app')
      Bundler.with_unbundled_env do
        # sh("rails _#{rails_version}_ new test_app -T")
        sh("gem install zeitwerk -v 2.6.18") if rails_version < '7'
        sh("gem install nokogiri -v 1.15.6") if rails_version < '7'
        sh("gem install net-imap -v 0.4.18") if rails_version < '7'
        sh("gem install concurrent-ruby -v 1.3.4") if rails_version < '7'
        sh("gem install foreman")
        sh("gem install rails --version=#{rails_version}")
        sh("gem uninstall net-imap --version '> 0.4.18'") if rails_version < '7'
        sh("gem uninstall concurrent-ruby --version '> 1.3.4'") if rails_version < '7'
        sh("rails _#{rails_version}_ new test_app -T")
      end
      Bundler.with_unbundled_env do
        Dir.chdir('test_app') do
          sh('cat ../gems.rb >> Gemfile')
          sh("echo 'gem \"opal\", \"#{opal_version}\"' >> Gemfile")
          sh("echo 'gem \"net-imap\", \"0.4.18\"' >> Gemfile")
          sh("echo 'gem \"concurrent-ruby\", \"1.3.4\"' >> Gemfile") # if rails_version < '7'
          sh("bundle update")
          sh("bundle binstubs bundler")
          sh("bundle exec rails webpacker:install")
          sh('spring stop')
          sh('bundle exec rails g hyperstack:install')
          sh('bundle exec rails generate model Sample name:string description:text')
          sleep 1
          sh('pwd')
          sh('ls app/models')
          sh('mv app/models/sample.rb app/hyperstack/models/sample.rb')
          sh("cat ../server_side_sample.rb >> app/models/sample.rb")
          sh('bundle exec rake db:migrate')
          sh('RAILS_ENV=test bundle exec rake db:setup')
          # sh('bundle exec rails dev:cache') # not tested yet...
          sh('RAILS_ENV=test bundle exec rails webpacker:compile')
        end
      end
    end
  end
end

task :default => :spec
