source 'https://rubygems.org'
#gem "opal-jquery", git: "https://github.com/opal/opal-jquery.git", branch: "master"
gem 'hyper-spec',       path: '../hyper-spec'
gem 'hyperstack-config', path: '../hyperstack-config'
gem 'hyper-state',      path: '../hyper-state'
gem 'hyper-component',  path: '../hyper-component'

# CI/test harness: pin transitive deps to versions compatible with react-rails
# (< 2.7.0). sprockets >= 4.2 raises "can't modify immutable cached environment";
# connection_pool >= 3.0 breaks react-rails' server-renderer pool.
gem 'sprockets', '~> 4.0', '< 4.2'
gem 'connection_pool', '< 3.0'

# Parallel specs: fan part2 specs across processes, one DB per process.
gem 'parallel_tests', group: [:development, :test]

gemspec

# Ruby 3.4 dropped several gems from the default set (now "bundled gems"), but
# Rails 6.1.7.x (activesupport) still requires them. Declare them explicitly so
# the bundle resolves on Ruby >= 3.4. See #11 (3.3 -> 3.4 bump).
gem 'bigdecimal'
gem 'mutex_m'
gem 'drb'
gem 'base64'
gem 'logger'
