require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec) do |t|
  t.rspec_opts = ENV['SPEC_OPTS'] if ENV['SPEC_OPTS']
end

namespace :spec do
  task :prepare do
    sh %(cd spec/test_app; bundle exec rails db:setup)
  end
end

task :default => :spec
