source 'https://rubygems.org'
gem 'hyper-state',      path: '../hyper-state'
gem 'hyper-component',  path: '../hyper-component'
gem 'hyper-operation',  path: '../hyper-operation'
gem 'hyper-spec', path: '../hyper-spec'
gem 'hyper-trace', path: '../hyper-trace'
gem 'hyperstack-config', path: '../hyperstack-config'
unless ENV['OPAL_VERSION']&.match("0.11")
  gem 'opal-browser', git: 'https://github.com/opal/opal-browser'
end

# CI/test harness: pin transitive deps to versions compatible with react-rails
# (< 2.7.0). sprockets >= 4.2 raises "can't modify immutable cached environment";
# connection_pool >= 3.0 breaks react-rails' server-renderer pool.
gem 'sprockets', '~> 4.0', '< 4.2'
gem 'connection_pool', '< 3.0'
gemspec
