source "https://gems.ru.aegean.gr"
source 'https://rubygems.org'
#gem "opal-jquery", git: "https://github.com/opal/opal-jquery.git", branch: "master"
gem 'hyper-spec',        path: '../hyper-spec'
gem 'hyperstack-config', path: '../hyperstack-config'
gem 'hyper-store',       path: '../hyper-store'
gem 'hyper-component',   path: '../hyper-component'
gem 'hyper-operation',   path: '../hyper-operation'
# Specify your gem's dependencies in hyper-console.gemspec

gemspec

# Ruby 3.4 dropped several gems from the default set (now "bundled gems"), but
# Rails 6.1.7.x (activesupport) still requires them. Declare them explicitly so
# the bundle resolves on Ruby >= 3.4. See #11 (3.3 -> 3.4 bump).
gem 'bigdecimal'
gem 'mutex_m'
gem 'drb'
gem 'base64'
gem 'logger'
